### ISSUE TITLE
should have an option to not follow symlinks

### ISSUE THREAD

**Issue by asquare** [rictorres/node-rpm-builder#14]
There should be an option to not follow symlinks (and preserve the link) when copying files to BUILDROOT.

**Comment by rictorres** [comment]
that's an interesting case, actually. i'm gonna have a look at this over the weekend!

**Comment by majgis** [comment]
Is this issue why I'm getting the following error while trying to copy node_modules/express?

```
Error: EEXIST, file already exists '../mime/cli.js'
    at Object.fs.symlinkSync (evalmachine.<anonymous>:742:18)
    at copySync (/home/mjackson/projects/beetlejuice/node_modules/rpm-builder/node_modules/fs-extra/lib/copy.js:91:8)
    at /home/mjackson/projects/beetlejuice/node_modules/rpm-builder/node_modules/fs-extra/lib/copy.js:86:7
    at Array.forEach (native)
    at copySync (/home/mjackson/projects/beetlejuice/node_modules/rpm-builder/node_modules/fs-extra/lib/copy.js:85:14)
    at /home/mjackson/projects/beetlejuice/node_modules/rpm-builder/node_modules/fs-extra/lib/copy.js:86:7
    at Array.forEach (native)
    at copySync (/home/mjackson/projects/beetlejuice/node_modules/rpm-builder/node_modules/fs-extra/lib/copy.js:85:14)
    at /home/mjackson/projects/beetlejuice/node_modules/rpm-builder/node_modules/fs-extra/lib/copy.js:86:7
    at Array.forEach (native)
```

Is there currenly a recommended work around?

**Comment by rictorres** [comment]
hey @majgis, i'm not really sure about your case.
i'm gonna update this module this week and will try to reproduce the issues described here :)

i'll let you guys know.

**Comment by ddequidt** [comment]
For the record, I encountered the issue.
I found a workaround by not creating those ./bin syslinks as I don't need them in the package.
Run `npm install --only=prod --no-bin-links` before building rpm.
